[BE] 　[FE]企業側の認証機能とsidebarなどのUI作成に対応する修正
ponsAoki/unite-api pull request #33
Opened 2023-07-12 15:19 UTC by nagayamajun

--概要
https://github.com/nagayamajun/unite-replace-front/pull/21
こちらがFEと対応するPRです！

2023-07-13 14:23 UTC, ponsAoki commented
@nagayamajun 
上に書いてくれてる懸念点に関してなんですが、
1. employeeのオブジェクト丸々返すでいいと思います！(そっちの方が、employeeの他のカラムが欲しいってなった時にも便利そう)
2.
``` 
return !!decodedToken && !!employee
```
のように返すか、
```
if (!decodedToken) return false;
.....
if (!employee) return false;
.....
return true
```
のように返すのでも良さそう。(コード的に読みやすそうな方でお願いします！🙇)

2023-07-15 05:08 UTC, nagayamajun commented
@ponsAoki 
テスト結果です🙇‍♀️

<img width="1728" alt="スクリーンショット 2023-07-15 14 08 41" src="https://github.com/ponsAoki/unite-api/assets/85071324/a33cae06-19ad-4bb1-96c6-404690e799a0">

2023-07-15 06:20 UTC, ponsAoki requested changes
@nagayamajun 
一旦コードベースでレビューしました！
・プロダクト関連のいいね機能とかは関心ごと的に認証とは別範囲だと思うので、できれば別PRに分けてもらいたいです🙇！
・タイポとかスペルミスがところどころある気がするので、VSCodeのCode Spell Checkerっていう拡張機能おすすめします！
https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker#:~:text=Open%20up%20VS%20Code%20and,and%20reload%20window%20to%20enable.

2023-07-15 06:20 UTC, ponsAoki commented on src/employee/use-case/create-employee-with-email.ts
>      //フロントにエラー文を送れるようにしたい。
このコメント削除でもいいですかね？

2023-07-15 06:20 UTC, ponsAoki commented on src/employee/use-case/create-employee-with-email.ts
> +      throw Error(`ユーザー登録に失敗しました: ${err}`);
エラーメッセージ定数化したい

2023-07-15 08:19 UTC, ponsAoki approved these changes
👍

2023-07-15 08:39 UTC, merged