[BE]ランキング機能の実装
ponsAoki/unite-api pull request #38
Opened 2023-07-18 13:42 UTC by nagayamajun

##概要
学生が作成した募集をランキング化する機能を作成しました。
ロジックとしては、
1.従業員がproductにいいねを押す
2.いいねの数を競う
2の実装に関してレンダリングが走るたびに毎度再計算を行うことはパフォーマンスを落とすことになると考えられるのでJob化しています。

##懸念点
cronの時間をどうするか？(今のPRでは確認しやすいように30秒と40秒に一回処理を走らせています)

##スクショ

<img width="1728" alt="スクリーンショット 2023-07-18 22 41 36" src="https://github.com/ponsAoki/unite-api/assets/85071324/b022bff6-f086-4654-83dd-98a04633dca0">

2023-07-20 11:38 UTC, ponsAoki requested changes
@nagayamajun 
お疲れ様です！
数点コメントしました！🙇

2023-07-20 11:38 UTC, ponsAoki commented on src/period-like-sum/use-case/create-or-update-like-sum.job.ts
> +        }
`PeriodLikeSumService`側で`upsert`するメソッドを作成して、それをここで呼んだらより可読性高くなると思います！
upsert: https://www.prisma.io/docs/concepts/components/prisma-client/crud#update-or-create-records

2023-07-20 11:38 UTC, ponsAoki commented on src/product/dto/create-product-input.ts
> +  headline!: string;
一応`@IsNotEmpty`でデコレートお願いします！

2023-07-20 11:38 UTC, ponsAoki commented on src/product/product.service.ts
> +          some: {}
ここの`some{}`ってどういう意図がありますか？

2023-07-20 11:38 UTC, ponsAoki commented on src/user-to-recruit-like/use-case/create-user-to-recruit-like.ts
> +      throw Error(ALREADY_EXISTS_LIKE);
`new Error()`でインスタンス化した方がいい気がします！
`InternalException()`でより意図を明確にするのもあり。
`BadRequestException()`とかが意図的には合ってるのかも。

2023-07-22 04:26 UTC, nagayamajun commented on src/product/product.service.ts
> +          some: {}
@ponsAoki 
関連するリレーションが少なくとも1つ以上存在するかどうかを確認していたんですけどsomeなして
{}だけで良さそうだったので変更しておきます🙇

2023-07-22 04:37 UTC, nagayamajun commented
@ponsAoki 
一旦修正だけpushしました！確認お願いします！
今からテスト書きます🔥🔥

2023-07-22 05:27 UTC, ponsAoki reviewed
@nagayamajun 
数点コメントしました！🙇

2023-07-22 05:27 UTC, ponsAoki commented on src/product/product.service.ts
> +        employeeToProductLikes: {}
ちょっとあんま理解できてないんですけど、これって「employeeToProductLikesが中身が空のオブジェクトであること」っていう条件にはならないんですね。
直感的には、
```
employeeToProductLikes: {
      some: {
        id: true,
      },
    },
```
とかって書くのかと思ってました

2023-07-22 05:27 UTC, ponsAoki commented on src/common/constants/message.ts
> +  '初めまして！\nぜひ一度話を聞いてみたいと思い、メッセージを送らせていただきました！';
この変更って最新のdevelop取り込んだ時に自動的に取り込まれませんでしたか？

2023-07-29 04:10 UTC, nagayamajun commented
テスト結果です🙇‍♀️

<img width="1728" alt="スクリーンショット 2023-07-29 13 06 40" src="https://github.com/ponsAoki/unite-api/assets/85071324/fcaa438e-57d4-44cf-bf6c-a63e44a926e2">

2023-07-29 04:13 UTC, nagayamajun commented
@ponsAoki 
まだ確認を容易にする為秒数自体を変更していないので問題なくてもマージは待っていただきたいです🙇‍♀️

2023-07-29 10:32 UTC, ponsAoki requested changes
@nagayamajun 
お疲れ様です！
数点コメントしました！🙇‍♂️

2023-07-29 10:32 UTC, ponsAoki commented on test/e2e/employee-to-product-like.e2e-spec.ts
> +describe('EmployeeToProductLike API', () => {
すでにいいねをしている場合のケース (`throw new ConflictException(ALREADY_EXISTS_LIKE);`でエラーがスローされるケース) のテストもお願いします🙇‍♂️

2023-07-29 10:32 UTC, ponsAoki commented on test/e2e/period-like-sum.e2e-spec.ts
> +            }
jsの`reduce()`メソッド使ってループさせてもいいかなと思いました
https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Global_Objects/Array/reduce

2023-07-29 10:32 UTC, ponsAoki commented on src/period-like-sum/period-like-sum.job.service.ts
> +  findAllToSortByFixedTime(): PrismaPromise<PeriodLikeSum[]> {
このメソッドって、リポジトリ層のperiod-like-sum.service.tsに定義したらうまく動かない感じですか？
インフラ層の`prismaService`叩いてるんでリポジトリ層に持っていくのが自然かなと思いました！

それか、
・`return this.prismaService.periodLikeSum.findMany({`以降をperiod-like-sum.service.tsに切り出す
・employee-to-product-like/cron/みたいなディレクトリに`PeriodLikeSumJobService`クラスを定義するファイル作成
とかどうでしょうか？

2023-07-29 10:32 UTC, ponsAoki commented on src/employee-to-product-like/employee-to-product-like.service.ts
> +  create(employeeId: string, productId: string): PrismaPromise<any> {
ここ返り値の型指定お願いします (`PrismaPromise<EmployeeToProductLike>`)

2023-07-29 10:32 UTC, ponsAoki commented on src/employee-to-product-like/employee-to-product-like.service.ts
> +  findOne(employeeId: string, productId: string) {
ここの返り値の型指定もお願いします

2023-07-29 10:32 UTC, ponsAoki commented on test/mock/corporation/corporateAuth.guard.mock.ts
> +      imageUrl: 'imageUrl10',
ここって`10`じゃなくて`0`のままじゃダメなんでしたっけ？

2023-08-06 05:34 UTC, nagayamajun commented
テスト結果です🙇
<img width="1728" alt="スクリーンショット 2023-08-06 14 32 43" src="https://github.com/ponsAoki/unite-api/assets/85071324/572caaa6-3031-454a-b65e-a13695aaf815">

2023-08-06 14:22 UTC, ponsAoki approved these changes
okだと思います！👍
あとコンフリクトの修正だけしてもらったらマージしてもらって大丈夫だと思います！

2023-08-06 14:22 UTC, ponsAoki commented
@nagayamajun

2023-08-06 16:58 UTC, merged