[BE] Product + Comment + UserToRecruitLike周りのテスト
ponsAoki/unite-api pull request #42
Opened 2023-08-05 02:22 UTC by nagayamajun

このブランチは今PR投げてるブランチからpullしたのですがどうすれば良いのでしょうか？🙇

2023-08-07 01:55 UTC, nagayamajun commented
@ponsAoki 
どこかのテストが落ちる事象を見ていただきたいです🙇

2023-08-07 05:27 UTC, ponsAoki requested changes
@nagayamajun 
数点コメントしました！
・ロジック内でFEにエラー内容を表示させるようなエラーハンドリングをしている場合は、エラーが返されるケースもテストする
・includeしたリレーションレコードも一緒に返される場合は、リレーションレコードの内容も検証したい
上記2点お願いします🙇

2023-08-07 05:27 UTC, ponsAoki commented on test/e2e/product.e2e-spec.ts
> +        })
`comment`とか`employeeToProductLikes`のリレーションレコードを取得できてるかの検証もしたいかもです！

2023-08-07 05:27 UTC, ponsAoki commented on test/e2e/comment.e2e-spec.ts
> +  describe('Post /comment', () => {
コメント作成失敗のケースも欲しいかもです

2023-08-07 05:27 UTC, ponsAoki commented on test/e2e/userToRecruitLike.e2e-spec.ts
ファイル名をケバブケース (user-to-recruit-like) に変更お願いします

2023-08-07 05:48 UTC, nagayamajun commented on test/e2e/product.e2e-spec.ts
> +  //質問する
@ponsAoki 
ここすみませんpostを自分が消してたところです🙇‍♀️

2023-08-08 11:39 UTC, ponsAoki requested changes
@nagayamajun 
ほんの少しだけコメントしました🙇‍♂️

2023-08-08 11:39 UTC, ponsAoki commented on src/product/models/product-with-likes-and-like-sum.ts
これ自分が「`models/`」て言ってたからこのディレクトリにしてくれたと思うんですけど、他のmoduleでは`entities/`で統一になっていたので、`entities/`に修正でお願いします🙇‍♂️

2023-08-08 11:39 UTC, ponsAoki commented on test/e2e/product.e2e-spec.ts
> +          });
ここって1行挟んでほぼ同じこと検証してる気がするんで、どちらか削ってもいい気がします。
「Internal server error」は多分FEにレスポンスとして返したいようなエラーメッセージではないですよね？

2023-08-08 14:44 UTC, nagayamajun commented on test/e2e/product.e2e-spec.ts
> +          });
@ponsAoki 
確かに何か特定のエラーの時だけ返せば良いということですね！

2023-08-08 14:54 UTC, ponsAoki approved these changes
@nagayamajun 
👍

2023-08-08 14:56 UTC, merged